In [170]:
import pandas as pd
import numpy as np

In [171]:
# Any results you write to the current directory are saved as output.
import itertools

# %matplotlib inline
# import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
# from sklearn.metrics import confusion_matrix

from tensorflow import keras
layers = keras.layers
models = keras.models

In [172]:
data = pd.read_csv("bbc-text.csv")

In [173]:
data 

category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
5          politics  howard hits back at mongrel jibe michael howar...
6          politics  blair prepares to name poll date tony blair is...
7             sport  henman hopes ended in dubai third seed tim hen...
8             sport  wilkinson fit to face edinburgh england captai...
9     entertainment  last star wars  not for children  the sixth an...
10    entertainment  berlin cheers for anti-nazi film a german movi...
11         business  virgin blue shares plummet 20% shares in austr...
12         business  crude oil prices back above $50 cold weather a...
13         politics  hague  given up  his pm ambition former conser...
14            sport  moya emotional after davis cup win carlos moya...
15         business  s korean credit card firm rescued south korea ...
16         politics  howard backs stem cell research michael howard...
17            sport  connors boost for british tennis former world ...
18         business  japanese banking battle at an end japan s sumi...
19             tech  games maker fights for survival one of britain...
20             tech  security warning over  fbi virus  the us feder...
21             tech  halo 2 heralds traffic explosion the growing p...
22            sport  bates seals takeover ken bates has completed h...
23            sport  cole faces lengthy injury lay-off aston villa ...
24             tech  mobile audio enters new dimension as mobile ph...
25            sport  moya fights back for indian title carlos moya ...
26    entertainment  career honour for actor dicaprio actor leonard...
27             tech  mobile gig aims to rock 3g forget about going ...
28         politics  terror suspects face house arrest uk citizens ...
29    entertainment  halloween writer debra hill dies screenwriter ...
...             ...                                                ...
2195          sport  owen delighted with real display michael owen ...
2196       business  gm issues 2005 profits warning general motors ...
2197       politics  campbell returns to election team ex-downing s...
2198       business  asian banks halt dollar s slide the dollar reg...
2199       business  wall street cool to ebay s profit shares in on...
2200           tech  uk pioneers digital film network the world s f...
2201       business  ban on forced retirement under 65 employers wi...
2202           tech  local net tv takes off in austria an austrian ...
2203       politics  profile: david miliband david miliband s rapid...
2204           tech  argonaut founder rebuilds empire jez san  the ...
2205  entertainment  dance music not dead says fatboy dj norman coo...
2206       politics  kennedy questions trust of blair lib dem leade...
2207           tech  california sets fines for spyware the makers o...
2208  entertainment  snicket tops us box office chart the film adap...
2209          sport  time to get tough on friendlies  for an intern...
2210       politics  teens  know little  of politics teenagers ques...
2211  entertainment  lopez misses uk charity premiere jennifer lope...
2212       business  christmas shoppers flock to tills shops all ov...
2213           tech  progress on new internet domains by early 2005...
2214       business  bush budget seeks deep cutbacks president bush...
2215           tech  junk e-mails on relentless rise spam traffic i...
2216  entertainment  top stars join us tsunami tv show brad pitt  r...
2217           tech  rings of steel combat net attacks gambling is ...
2218          sport  davies favours gloucester future wales hooker ...
2219       business  beijingers fum

In [174]:
data.shape

(2225, 2)

In [175]:
data.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [176]:
data['category'].value_counts()

sport            511
business         510
politics         417
tech             401
entertainment    386
Name: category, dtype: int64

In [177]:
train_size = int(len(data) * .8)
print ("Train size: %d" % train_size)
print ("Test size: %d" % (len(data) - train_size))

Train size: 1780
Test size: 445


In [178]:
def train_test_split(data, train_size):
    train = data[:train_size]
    test = data[train_size:]
    return train, test

In [179]:
train_cat, test_cat = train_test_split(data['category'], train_size)
train_text, test_text = train_test_split(data['text'], train_size)

In [180]:
train_cat

0                tech
1            business
2               sport
3               sport
4       entertainment
5            politics
6            politics
7               sport
8               sport
9       entertainment
10      entertainment
11           business
12           business
13           politics
14              sport
15           business
16           politics
17              sport
18           business
19               tech
20               tech
21               tech
22              sport
23              sport
24               tech
25              sport
26      entertainment
27               tech
28           politics
29      entertainment
            ...      
1750            sport
1751    entertainment
1752    entertainment
1753         business
1754             tech
1755             tech
1756         business
1757             tech
1758         business
1759         business
1760            sport
1761            sport
1762         politics
1763            sport
1764      

In [181]:
test_cat

1780    entertainment
1781             tech
1782         politics
1783            sport
1784            sport
1785             tech
1786         business
1787             tech
1788    entertainment
1789    entertainment
1790         politics
1791         politics
1792         business
1793    entertainment
1794            sport
1795    entertainment
1796    entertainment
1797         business
1798            sport
1799         politics
1800             tech
1801         business
1802            sport
1803    entertainment
1804             tech
1805         politics
1806         politics
1807            sport
1808            sport
1809         business
            ...      
2195            sport
2196         business
2197         politics
2198         business
2199         business
2200             tech
2201         business
2202             tech
2203         politics
2204             tech
2205    entertainment
2206         politics
2207             tech
2208    entertainment
2209      

In [182]:
train_text

0       tv future in the hands of viewers with home th...
1       worldcom boss  left books alone  former worldc...
2       tigers wary of farrell  gamble  leicester say ...
3       yeading face newcastle in fa cup premiership s...
4       ocean s twelve raids box office ocean s twelve...
5       howard hits back at mongrel jibe michael howar...
6       blair prepares to name poll date tony blair is...
7       henman hopes ended in dubai third seed tim hen...
8       wilkinson fit to face edinburgh england captai...
9       last star wars  not for children  the sixth an...
10      berlin cheers for anti-nazi film a german movi...
11      virgin blue shares plummet 20% shares in austr...
12      crude oil prices back above $50 cold weather a...
13      hague  given up  his pm ambition former conser...
14      moya emotional after davis cup win carlos moya...
15      s korean credit card firm rescued south korea ...
16      howard backs stem cell research michael howard...
17      connor

In [183]:
test_text

1780    hobbit picture  four years away  lord of the r...
1781    game firm holds  cast  auditions video game fi...
1782    clarke plans migrant point scheme anyone plann...
1783    radcliffe will compete in london paula radclif...
1784    serena becomes world number two serena william...
1785    ultimate game  award for doom 3 sci-fi shooter...
1786    algeria hit by further gas riots algeria suffe...
1787    fast lifts rise into record books two high-spe...
1788    muslim group attacks tv drama 24 a british mus...
1789    us tv special for tsunami relief a us televisi...
1790    brown names 16 march for budget chancellor gor...
1791    choose hope over fear - kennedy voters will ha...
1792    worldcom bosses  $54m payout ten former direct...
1793    de niro film leads us box office film star rob...
1794    robinson ready for difficult task england coac...
1795    us tv cuts nudity from bbc film a us tv networ...
1796    french honour for director parker british film...
1797    stando

## Tokenizer

Class for vectorizing texts, or/and turning texts into sequences (=list of word indexes, where the word of rank i in the dataset (starting at 1) has index i).


In [184]:
#example for tokenizer
#zero index is reserved for padding
#Tokenize meaning : break (text) into individual linguistic units.
#zero in matrix is reserved for Embedding Layer

from keras.preprocessing.text import Tokenizer
tok = Tokenizer()
#tok = Tokenizer(num_words=10, char_level=False)
tok.fit_on_texts(["this comment is not toxic"]) 
print(tok.texts_to_sequences(["this comment is not toxic"])) 
print(tok.texts_to_sequences(["this very long comment is  toxic"]))
print(tok.texts_to_matrix(["this comment is not toxic"]))

[[1, 2, 3, 4, 5]]
[[1, 2, 3, 5]]
[[0. 1. 1. 1. 1. 1.]]


In [185]:
max_words = 1000
tokenize = keras.preprocessing.text.Tokenizer(num_words=max_words, char_level=False)
#tokenize = keras.preprocessing.text.Tokenizer()

In [186]:
# tokenize

In [187]:
tokenize.fit_on_texts(train_text)

In [188]:
x_train = tokenize.texts_to_matrix(train_text)
x_test = tokenize.texts_to_matrix(test_text)

In [189]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [190]:
x_train[0]

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0.

In [191]:
print(len(x_train[0]))
print(len(x_train[0]))

1000
1000


In [192]:
x_train.shape

(1780, 1000)

In [193]:
x_test.shape

(445, 1000)

In [194]:
train_cat

0                tech
1            business
2               sport
3               sport
4       entertainment
5            politics
6            politics
7               sport
8               sport
9       entertainment
10      entertainment
11           business
12           business
13           politics
14              sport
15           business
16           politics
17              sport
18           business
19               tech
20               tech
21               tech
22              sport
23              sport
24               tech
25              sport
26      entertainment
27               tech
28           politics
29      entertainment
            ...      
1750            sport
1751    entertainment
1752    entertainment
1753         business
1754             tech
1755             tech
1756         business
1757             tech
1758         business
1759         business
1760            sport
1761            sport
1762         politics
1763            sport
1764      

In [195]:
test_cat

1780    entertainment
1781             tech
1782         politics
1783            sport
1784            sport
1785             tech
1786         business
1787             tech
1788    entertainment
1789    entertainment
1790         politics
1791         politics
1792         business
1793    entertainment
1794            sport
1795    entertainment
1796    entertainment
1797         business
1798            sport
1799         politics
1800             tech
1801         business
1802            sport
1803    entertainment
1804             tech
1805         politics
1806         politics
1807            sport
1808            sport
1809         business
            ...      
2195            sport
2196         business
2197         politics
2198         business
2199         business
2200             tech
2201         business
2202             tech
2203         politics
2204             tech
2205    entertainment
2206         politics
2207             tech
2208    entertainment
2209      

In [196]:
#Understanding encoder

from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [197]:
le.fit(["paris", "paris", "tokyo", "amsterdam"])
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [198]:
print(le.transform(["amsterdam", "tokyo", "paris"]))
list(le.inverse_transform([2, 2, 1]))

[0 2 1]


['tokyo', 'tokyo', 'paris']

In [199]:
encoder = LabelEncoder()
encoder.fit(train_cat)
y_train = encoder.transform(train_cat)
y_test = encoder.transform(test_cat)

In [200]:
y_train

array([4, 0, 3, ..., 3, 0, 1])

In [201]:
len(y_train)

1780

In [202]:
y_test

array([1, 4, 2, 3, 3, 4, 0, 4, 1, 1, 2, 2, 0, 1, 3, 1, 1, 0, 3, 2, 4, 0,
       3, 1, 4, 2, 2, 3, 3, 0, 0, 0, 0, 0, 1, 0, 2, 2, 4, 4, 1, 2, 1, 0,
       2, 3, 3, 0, 4, 0, 4, 3, 0, 0, 2, 3, 3, 2, 2, 1, 1, 2, 0, 2, 2, 0,
       4, 2, 2, 2, 2, 2, 1, 1, 4, 2, 3, 2, 3, 4, 3, 3, 3, 1, 4, 1, 4, 3,
       4, 3, 3, 1, 1, 0, 1, 1, 2, 0, 3, 4, 4, 2, 0, 3, 0, 1, 3, 2, 1, 3,
       3, 0, 2, 4, 4, 0, 0, 3, 2, 1, 3, 3, 2, 1, 4, 3, 1, 0, 2, 3, 2, 4,
       1, 3, 2, 0, 1, 2, 1, 2, 3, 2, 0, 0, 2, 0, 4, 3, 0, 1, 0, 3, 3, 1,
       4, 2, 4, 2, 2, 3, 3, 3, 0, 4, 1, 0, 3, 0, 3, 0, 4, 0, 0, 0, 0, 3,
       3, 3, 0, 0, 1, 0, 0, 0, 3, 3, 3, 4, 0, 3, 3, 3, 0, 1, 4, 4, 4, 2,
       0, 0, 4, 0, 4, 3, 3, 2, 2, 2, 3, 3, 2, 2, 4, 0, 3, 3, 3, 3, 0, 3,
       0, 0, 0, 0, 3, 2, 3, 4, 4, 3, 4, 0, 1, 0, 3, 0, 4, 4, 2, 1, 0, 1,
       0, 4, 2, 1, 2, 1, 1, 4, 0, 4, 4, 0, 2, 3, 1, 0, 2, 1, 0, 4, 3, 4,
       2, 3, 2, 0, 2, 2, 0, 0, 0, 4, 2, 0, 2, 0, 1, 2, 3, 2, 2, 3, 1, 4,
       4, 0, 4, 3, 0, 0, 2, 3, 4, 4, 4, 3, 1, 3, 2,

In [203]:
len(y_train)

1780

In [204]:
num_classes = np.max(y_train) + 1

In [205]:
num_classes

5

In [206]:
# Consider an array of 5 labels out of a set of 3 classes {0, 1, 2}:
labels = np.array([0, 2, 1, 2, 0])
# `to_categorical` converts this into a matrix with as many
# columns as there are classes. The number of rows
# stays the same.
keras.utils.to_categorical(labels)

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [207]:
# Converts the labels to a one-hot representation
num_classes = np.max(y_train) + 1
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [208]:
batch_size = 32
epochs = 4
drop_ratio = 0.5

In [209]:
model = models.Sequential()
model.add(layers.Dense(512, input_shape=(max_words,)))
model.add(layers.Dense(212 , activation = 'relu'))
model.add(layers.Activation('relu'))
model.add(layers.Dense(num_classes))
model.add(layers.Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [213]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [214]:
y_train

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [210]:
history = model.fit(x_train, y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_split=0.1)

Train on 1602 samples, validate on 178 samples
Epoch 1/4
1602/1602 [==============================] - 0s 258us/sample - loss: 0.3461 - acc: 0.8989 - val_loss: 0.1799 - val_acc: 0.9326
Epoch 2/4
1602/1602 [==============================] - 0s 175us/sample - loss: 0.0281 - acc: 0.9944 - val_loss: 0.1255 - val_acc: 0.9438
Epoch 3/4
1602/1602 [==============================] - 0s 174us/sample - loss: 0.0034 - acc: 1.0000 - val_loss: 0.1261 - val_acc: 0.9494
Epoch 4/4
1602/1602 [==============================] - 0s 176us/sample - loss: 0.0014 - acc: 1.0000 - val_loss: 0.1245 - val_acc: 0.9551


In [211]:
score = model.evaluate(x_test, y_test,batch_size=batch_size, verbose=1)

445/445 [==============================] - 0s 76us/sample - loss: 0.1587 - acc: 0.9573


In [212]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.15873410139191016
Test accuracy: 0.95730335


In [ ]:
#model.predict(x_train[0])
#x_train[0].shape

# Hyperparameter tunning

This is a good time to go back and tweak some parameters such as epoch, batch size, dropout ratio, network structure, activation function, and others, to see if you can improve the accuracy.

In this particular case, to make it more challenging, I recommend reducing the max words of the call to keras.preprocessing.text.Tokenizer. This will reduce the number of words for each input sample, thus making it more challenging to accurately predict the category. (Notice that not all hyperparameters are necessarily inside the model. This is one such example.)

The default was up to 1000 words per article. See what happens when you reduce that number to 200 words, or 50 words, or even fewer. As the evaluation accuracy drops, the effects of your hyperparameter tuning will be more pronounced, with successful adjustments making meaningful improvements to the model performance.

To make this process easier to manage, I've encapulated the model definition and training and evaluation calls into one function call. You can add additional parameters as needed.

In [ ]:
#by using hyperprameter tunning

def run_experiment(batch_size, epochs, drop_ratio):
    print('batch size: {}, epochs: {}, drop_ratio: {}'.format(batch_size, epochs, drop_ratio))
    model = models.Sequential()
    model.add(layers.Dense(512, input_shape=(max_words,)))
    model.add(layers.Activation('relu'))
    model.add(layers.Dropout(drop_ratio))
    model.add(layers.Dense(num_classes))
    model.add(layers.Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=0,
                    validation_split=0.1)
    score = model.evaluate(x_test, y_test,
                       batch_size=batch_size, verbose=0)
    print('\tTest loss:', score[0])
    print('\tTest accuracy:', score[1])

In [ ]:
batch_size = 16
epochs = 4
drop_ratio = 0.4
run_experiment(batch_size, epochs, drop_ratio)

In [ ]:
text_labels = encoder.classes_
text_labels

In [ ]:
#model.predict?
#It predicts the probablity according to classes i.e business, entertainment etc ...
prediction = model.predict(np.array([x_test[0]]))
prediction

In [ ]:
predicted_label = text_labels[np.argmax(prediction)]
predicted_label

In [ ]:
text_labels = encoder.classes_

for i in range(10):
    prediction = model.predict(np.array([x_test[i]]))
    predicted_label = text_labels[np.argmax(prediction)]
    print(test_text.iloc[i][:50], "...")
    print('Actual label:' + test_cat.iloc[i])
    print("Predicted label: " + predicted_label + "\n")  

In [ ]:
test_text.iloc[3]

In [ ]:
prediction = model.predict(np.array([x_test[3]]))

In [ ]:
prediction

In [ ]:
predicted_label = text_labels[np.argmax(prediction)]
predicted_label

In [ ]:
#print(test_text.iloc[:50], "...")
print('Actual label:' + test_cat.iloc[3])
print("Predicted label: " + predicted_label + "\n") 